### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by FFY00** [evernote/evernote-sdk-python#57]
```
Obtaining file:///home/anubis/git/evernote-sdk-python/src/evernote-sdk-python-1.28
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/anubis/git/evernote-sdk-python/src/evernote-sdk-python-1.28/setup.py", line 22
        packages=find_packages('lib',exclude=["*.thrift", "*.thrift.*", "thrift.*", "thrift"]),
    SyntaxError: keyword argument repeated
```

**Comment by FFY00** [comment]
Here's my fix: https://aur.archlinux.org/cgit/aur.git/tree/evernote-sdk-python-1.28-fix-setup.patch?h=evernote-sdk-python

Stolen from @matthewayne's frok.
