### ISSUE TITLE
pip install evernote | Error

### ISSUE THREAD

**Issue by ronething** [evernote/evernote-sdk-python#61]
Collecting evernote
  Downloading http://mirrors.aliyun.com/pypi/packages/f9/6b/877f8edef8ef040d32eb38f3bf6322ba334de9d10614d8db9d869c162fc1/evernote-1.25.3.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 64kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xr/8kys7jh56tn91lhc_72nh_wh0000gn/T/pip-install-f2tcrxsw/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xr/8kys7jh56tn91lhc_72nh_wh0000gn/T/pip-install-f2tcrxsw/evernote/

**Comment by ronething** [comment]
![image](https://user-images.githubusercontent.com/28869910/46711845-c0f59400-cc80-11e8-9796-255dea16259d.png)

**Comment by ronething** [comment]
my fault sorry.
