### ISSUE TITLE
I get this error `EDAMSystemException`

### ISSUE THREAD

**Issue by JiaxiangBU** [evernote/evernote-sdk-python#64]
```
EDAMSystemException: EDAMSystemException(errorCode=8, rateLimitDuration=None, _message='authenticationToken')
````

<details>
<summary>I get this error `EDAMSystemException`</summary>

```
---------------------------------------------------------------------------
EDAMSystemException                       Traceback (most recent call last)
<ipython-input-7-9908879e9b22> in <module>()
      2 client = EvernoteClient(token=dev_token)
      3 userStore = client.get_user_store()
----> 4 user = userStore.getUser()
      5 print user.username

C:\ProgramData\Miniconda3\envs\evernote-use-py2\lib\site-packages\evernote\api\client.pyc in delegate_method(*args, **kwargs)
    149                 return functools.partial(
    150                     targetMethod, authenticationToken=self.token
--> 151                 )(**dict(zip(arg_names, args)))
    152             else:
    153                 return targetMethod(*args, **kwargs)

C:\ProgramData\Miniconda3\envs\evernote-use-py2\lib\site-packages\evernote\edam\userstore\UserStore.pyc in getUser(self, authenticationToken)
   1031     """
   1032     self.send_getUser(authenticationToken)
-> 1033     return self.recv_getUser()
   1034 
   1035   def send_getUser(self, authenticationToken):

C:\ProgramData\Miniconda3\envs\evernote-use-py2\lib\site-packages\evernote\edam\userstore\UserStore.pyc in recv_getUser(self)
   1056       raise result.userException
   1057     if result.systemException is not None:
-> 1058       raise result.systemException
   1059     raise TApplicationException(TApplicationException.MISSING_RESULT, "getUser failed: unknown result");
   1060 

EDAMSystemException: EDAMSystemException(errorCode=8, rateLimitDuration=None, _message='authenticationToken')
```

</details>

**Comment by nicholasurban** [comment]
I do too.

**Comment by kentsx** [comment]
I'm using yingxiang (China version of Evernote). 
When running the sample, I changed `line 40 china = True`, but I still got following errors:

the token yinxiang gave me is in this format (I randomly changed a bit for this issue only): 
```
S=s1:U=132:E=170adafd4b:C=170sdfdsaf70:P=1cd:A=en-devtoken:V=2:H=9072e461cf4e6cddafda
```
I copied whole string to `auth_token =  `

BTW, I'm in the sandbox mode and not in the production mode
```
C:\python EDAMTest.py
Is my Evernote API version up to date?  True

Traceback (most recent call last):
  File "EDAMTest.py", line 56, in <module>
    note_store = client.get_note_store()
  File "C:\Users\xxxxl\AppData\Local\Programs\Python\Python37\lib\site-packages\evernote3-1.25.0-py3.7.egg\evernote\api\client.py", line 106, in get_note_store
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\evernote3-1.25.0-py3.7.egg\evernote\api\client.py", line 167, in delegate_method
  File "C:\Users\xxxl\AppData\Local\Programs\Python\Python37\lib\site-packages\evernote3-1.25.0-py3.7.egg\evernote\edam\userstore\UserStore.py", line 1156, in getNoteStoreUrl
  File "C:\Users\xxxl\AppData\Local\Programs\Python\Python37\lib\site-packages\evernote3-1.25.0-py3.7.egg\evernote\edam\userstore\UserStore.py", line 1181, in recv_getNoteStoreUrl
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(message='authenticationToken', errorCode=8, rateLimitDuration=None)
```

**Comment by kentsx** [comment]
> ```
> EDAMSystemException: EDAMSystemException(errorCode=8, rateLimitDuration=None, _message='authenticationToken')
> ```
> 
> I get this error `EDAMSystemException`

If you get this error coz you're using yingxiang, instead of evernote. Then I think I find the solution to this issue: 
> problem caused by the wrong server_host.
Go to the `~\evernote\lib\evernote\api\client.py`

locate  and change (should be around line 25)
```
        if self.sandbox:
            default_service_host = 'sandbox.evernote.com'   
                          #change it to 'sandbox.yinxiang.com'
```

I find this solution by registered an evernote dev and find the codes are fine with their server.

**Comment by yang-zhang-syd** [comment]
If you are running the code with production token, you will need to set the sandbox flag to false. 

`client = EvernoteClient(token=dev_token, sandbox=False)`

**Comment by curryhendry** [comment]
同样的问题，这个方法也是无效。

**Comment by vitaly-zdanevich** [comment]
Try fork that works for me https://github.com/JackonYang/evernote2

**Comment by curryhendry** [comment]
> Try fork that works for me https://github.com/JackonYang/evernote2

非常感谢，确实可以导出部分的yinxaing笔记，但是我在转换成md的时候也不太顺利。所以我最终还是放弃了，手动迁移。同时在过程中学习obsidian的用法。再次感谢！
Thank you very much. Indeed, I was able to export some of the Yinxiang notes, but I encountered difficulties when converting them to markdown (md). So, I ultimately gave up and decided to migrate them manually. Meanwhile, I learned how to use Obsidian during the process. Thanks again!
